// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: metric_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=go_metric.MetricType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetric) Reset() {
	*x = GetMetric{}
	mi := &file_metric_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetric) ProtoMessage() {}

func (x *GetMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metric_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetric.ProtoReflect.Descriptor instead.
func (*GetMetric) Descriptor() ([]byte, []int) {
	return file_metric_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_UNRECOGNIZED
}

func (x *GetMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetric) Reset() {
	*x = UpdateMetric{}
	mi := &file_metric_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetric) ProtoMessage() {}

func (x *UpdateMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metric_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetric.ProtoReflect.Descriptor instead.
func (*UpdateMetric) Descriptor() ([]byte, []int) {
	return file_metric_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetric) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_metric_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_metric_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchUpdateMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        []*Metric              `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateMetric) Reset() {
	*x = BatchUpdateMetric{}
	mi := &file_metric_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMetric) ProtoMessage() {}

func (x *BatchUpdateMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metric_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMetric.ProtoReflect.Descriptor instead.
func (*BatchUpdateMetric) Descriptor() ([]byte, []int) {
	return file_metric_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchUpdateMetric) GetMetric() []*Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type BatchUpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateMetricResponse) Reset() {
	*x = BatchUpdateMetricResponse{}
	mi := &file_metric_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMetricResponse) ProtoMessage() {}

func (x *BatchUpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_metric_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_metric_service_proto protoreflect.FileDescriptor

const file_metric_service_proto_rawDesc = "" +
	"\n" +
	"\x14metric_service.proto\x12\tgo_metric\x1a\fmetric.proto\"J\n" +
	"\tGetMetric\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.go_metric.MetricTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\fUpdateMetric\x12)\n" +
	"\x06metric\x18\x01 \x01(\v2\x11.go_metric.MetricR\x06metric\"Q\n" +
	"\x0eMetricResponse\x12)\n" +
	"\x06metric\x18\x01 \x01(\v2\x11.go_metric.MetricR\x06metric\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x11BatchUpdateMetric\x12)\n" +
	"\x06metric\x18\x01 \x03(\v2\x11.go_metric.MetricR\x06metric\"1\n" +
	"\x19BatchUpdateMetricResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xd2\x01\n" +
	"\aMetrics\x126\n" +
	"\x03Get\x12\x14.go_metric.GetMetric\x1a\x19.go_metric.MetricResponse\x12<\n" +
	"\x06Update\x12\x17.go_metric.UpdateMetric\x1a\x19.go_metric.MetricResponse\x12Q\n" +
	"\vBatchUpdate\x12\x1c.go_metric.BatchUpdateMetric\x1a$.go_metric.BatchUpdateMetricResponseB\x0eZ\fmetric/protob\x06proto3"

var (
	file_metric_service_proto_rawDescOnce sync.Once
	file_metric_service_proto_rawDescData []byte
)

func file_metric_service_proto_rawDescGZIP() []byte {
	file_metric_service_proto_rawDescOnce.Do(func() {
		file_metric_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_service_proto_rawDesc), len(file_metric_service_proto_rawDesc)))
	})
	return file_metric_service_proto_rawDescData
}

var file_metric_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metric_service_proto_goTypes = []any{
	(*GetMetric)(nil),                 // 0: go_metric.GetMetric
	(*UpdateMetric)(nil),              // 1: go_metric.UpdateMetric
	(*MetricResponse)(nil),            // 2: go_metric.MetricResponse
	(*BatchUpdateMetric)(nil),         // 3: go_metric.BatchUpdateMetric
	(*BatchUpdateMetricResponse)(nil), // 4: go_metric.BatchUpdateMetricResponse
	(MetricType)(0),                   // 5: go_metric.MetricType
	(*Metric)(nil),                    // 6: go_metric.Metric
}
var file_metric_service_proto_depIdxs = []int32{
	5, // 0: go_metric.GetMetric.type:type_name -> go_metric.MetricType
	6, // 1: go_metric.UpdateMetric.metric:type_name -> go_metric.Metric
	6, // 2: go_metric.MetricResponse.metric:type_name -> go_metric.Metric
	6, // 3: go_metric.BatchUpdateMetric.metric:type_name -> go_metric.Metric
	0, // 4: go_metric.Metrics.Get:input_type -> go_metric.GetMetric
	1, // 5: go_metric.Metrics.Update:input_type -> go_metric.UpdateMetric
	3, // 6: go_metric.Metrics.BatchUpdate:input_type -> go_metric.BatchUpdateMetric
	2, // 7: go_metric.Metrics.Get:output_type -> go_metric.MetricResponse
	2, // 8: go_metric.Metrics.Update:output_type -> go_metric.MetricResponse
	4, // 9: go_metric.Metrics.BatchUpdate:output_type -> go_metric.BatchUpdateMetricResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metric_service_proto_init() }
func file_metric_service_proto_init() {
	if File_metric_service_proto != nil {
		return
	}
	file_metric_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_service_proto_rawDesc), len(file_metric_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metric_service_proto_goTypes,
		DependencyIndexes: file_metric_service_proto_depIdxs,
		MessageInfos:      file_metric_service_proto_msgTypes,
	}.Build()
	File_metric_service_proto = out.File
	file_metric_service_proto_goTypes = nil
	file_metric_service_proto_depIdxs = nil
}
